---
title: "Loan_EDLD_652_Homework1"
author: "Christopher Loan"
date: "2/1/2021"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r include=FALSE}
library(tidyverse)
library(rio)
library(here)
```

```{r}
courses <- import(here("Data", "courses.csv"))
assessments <- import(here("Data", "assessments.csv"))
vle <- import(here("Data", "vle.csv"))
student_info <- import(here("Data", "studentInfo.csv"))
student_reg <- import(here("Data", "studentRegistration.csv"))
#student_vle <- import(here("Data", "studentVle.csv"))
student_assessment <- import(here("Data", "studentAssessment.csv"))
```

```{r eval=FALSE, include=FALSE}
courses %>% 
  count(code_module, code_presentation) %>% 
  filter(n > 1)

assessments %>% 
  count(id_assessment) %>% 
  filter(n > 1)

student_info %>% 
  count(id_student, code_presentation, code_module) %>% 
  filter(n > 1)

student_reg %>% 
  count(id_student, code_presentation, code_module) %>% 
  filter(n > 1)

student_assessment %>% 
  count(id_student, id_assessment) %>% 
  filter(n > 1)

# DA: Really nice job identifying the keys
```

# 1. 3 Mutating Joins

## first join

```{r echo=TRUE}
course_assessments <- courses %>% 
  full_join(assessments, by = c('code_module', 'code_presentation'))

# I know it's tempting to go toward full joins so you don't lose data but your
# datasets can become *so* messy if you always use full joins. As a general 
# rule, I would try to avoid full joins and only do them when they are 
# absolutely neccessary. Generally, you have one dataset that you're 
# prioritizing over the others, and you're just adding data to that dataset
```

## second join

```{r echo=TRUE}
students <- student_reg %>% 
  left_join(student_info, 
            by = c("id_student", 'code_presentation', 'code_module'))

# try to not go beyond 80 characters
```

## third join

```{r echo=TRUE}
stu_courses <- student_info %>% 
  full_join(courses, by = c('code_module', 'code_presentation'))
```

# 2. Filtering Joins

```{r echo=TRUE}
B_courses <- courses %>% slice(str_which(code_presentation, "B"))

# The above is interesting and efficient, but fairly non-standard. I would do 
# the same thing by passing a logical to `filter`. Something like

# courses %>% 
#   filter(grepl("B$", code_presentation))

# The dollar sign there just says the B needs to be at the end (just to be
# extra safe) and I'm using `grepl()` because it explicitly returns a logical.
# you could also use `stringr::str_detect()`, which is basically equivalent.

# To be clear, there's nothing wrong with the way you did it, and I actually
# kind of like it, but it just kind of surprised me so I thought I'd show you
# how I would typically do the same thing.

```

## only B courses

```{r echo=TRUE}
B_course_students <- students %>% 
  semi_join(B_courses)

B_course_students %>% 
  select(code_presentation) %>% 
  table()

# I'd suggest using count instead
B_course_students %>% 
  count(code_presentation)
```

## only J courses

```{r echo=TRUE}
J_course_students <- students %>% 
  anti_join(B_courses)

J_course_students %>% 
  select(code_presentation) %>% 
  table()

# Very nice example!
```

# 3. Create 3 Data Displays

## data display 1

```{r}
student_assessment %>% 
  mutate(assess_fct = factor(id_assessment)) %>% 
  group_by(assess_fct) %>% 
  summarize(average_score = mean(score), 
            se = sd(score)/sqrt(n())) %>% 
  arrange(desc(average_score)) %>% 
  slice(1:20) %>% 
  ggplot(aes(y = fct_reorder(assess_fct, average_score), 
             x = average_score, 
             xmin = average_score - se, 
             xmax = average_score + se)) +
  geom_col(alpha = 0.7, fill = 'coral3') + 
  geom_errorbar() +
  theme_minimal(base_size = 18) +
  labs(title = 'Twenty Easiest Assessments', 
       subtitle = 'Error bars represent Standard Error of Mean', 
       y = 'Assessment Label',
       x = 'Average Score') + 
  theme(axis.text.y = element_text(angle = 25), 
        plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic'), 
        plot.title.position = "plot")

# Very nice! I'd probably put what you have as the subtitle currently
# as a caption. You might also consider using 
# `scale_x_continuous(expand = c(0, 0))` to get rid of the excess white space. 
```

## data display 2

```{r}
stu_courses %>% 
   mutate(`Geographic Region` = 
           str_replace(string = region, pattern = " Region", "")) %>% 
  ggplot(aes(y = final_result)) + 
  geom_bar(show.legend = F, fill = 'coral3', alpha = 0.7) +
  facet_wrap(~`Geographic Region`) + 
  theme_minimal(base_size = 12) +
  theme(axis.text.y = element_text(angle = 25), 
        plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic'), 
        plot.title.position = "plot") +
  labs(x = 'Number of Students', 
       y = 'Status at end of course', 
       title = 'Counts of course outcomes, faceted by student location', 
       subtitle = 'Each facet represents the region that each student lived in during the course'
       )

# Also very nice!
```

## data display 3

```{r}
stu_courses %>% 
  mutate(`Geographic Region` = 
           str_replace(string = region, pattern = " Region", "")) %>% 
  filter(final_result == 'Fail') %>% 
  ggplot(aes(y = `Geographic Region`, fill = age_band)) +
  geom_bar() + 
  facet_wrap(~gender, labeller = as_labeller(c(F = 'Female', M ='Male'))) + 
  theme_minimal(base_size = 18) + 
  labs(#y = 'Geographic Region', 
       title = 'Identifying students that need more support',
       subtitle = 'Number of failured courses by intersection of student information', 
       x = 'Number of Failed Courses',
       fill = 'Student Age') +
  scale_fill_viridis_d() + 
  theme(axis.text.y = element_text(angle = 25), 
        plot.title = element_text(face = 'bold'),
        plot.subtitle = element_text(face = 'italic'), 
        plot.title.position = "plot")

# I like this one a lot too but it feels like the bar stacking is in 
# reverse order. Also shouldn't it be >= 55?
```

# Reproducing Plots

```{r}
plot_dat <- assessments %>% 
  filter(assessment_type == 'TMA') %>% 
  left_join(student_assessment, by = 'id_assessment') %>% 
  left_join(student_info, by = c('code_module', 'code_presentation', 'id_student')) 
```

```{r fig.height=12}
plot_dat %>%  na.omit() %>% 
  group_by(gender, highest_education, final_result) %>% 
  mutate(average_TMA = mean(score)) %>% 
  ggplot(aes(x = average_TMA, 
             y = fct_reorder(highest_education, average_TMA))) +
  theme_minimal(base_size = 20) + 
  geom_line(aes(group = highest_education),
            size = 3, 
            color = 'gray30') + 
  geom_point(aes(group = gender, 
             color = gender), 
             size = 5)+
  facet_wrap(~fct_reorder(final_result, average_TMA), ncol = 1)+ 
  labs(title = 'Average TMA Scores', 
       subtitle = 'Results displayed by education, gender, and final results designation', 
       y = 'Highest Education', 
       x = 'Average Score', 
       color = "Gender", 
       caption = 'Data from Kuzilek, Hlosta, & Zdrahal (2017).\nhttps://analyse.kmi.open.ac.uk/open_dataset') + 
  scale_colour_brewer(guide = "legend") +
  theme(legend.position = "bottom")

# Looks good!
```
